In [1]:
import pandas as pd

In [31]:
# Read in joined_wDistance.csv
df = pd.read_csv('joined_wDistance.csv')
# Drop first two columns
df = df.drop(df.columns[0:2], axis=1)
df

,Name,Wait Time,Delivery Fee,Link,Delivery Address,Geoid,Unnamed: 0.1.1,Countyfp,Blkgrpce,Funcstat,...,City,State,County,Zip,Country,Source,Restaurant Address,Restaurant Latitude,Restaurant Longitude,Distance
0,Philly's Best (Jingletown),NaN,4.99,https://postmates.com/store/phillys-best-jingl...,2236 Linden St Oakland CA,60014016002,42,1,2,S,...,Oakland,CA,Alameda County,94607,US,Alameda,"2353 East 12th Street, Oakland, CA 94601",37.781594,-122.235954,3.423599
1,Burger Latino (5333 Adeline St),35–45 min,3.99,https://postmates.com/store/burger-latino-5333...,2236 Linden St Oakland CA,60014016002,42,1,2,S,...,Oakland,CA,Alameda County,94607,US,Alameda,"5333 Adeline St, Oakland, CA 94608",37.838429,-122.275828,1.584193
2,"Philly Fresh Cheesesteaks (5333 Adeline St ,)",35–45 min,3.99,https://postmates.com/store/philly-fresh-chees...,2236 Linden St Oakland CA,60014016002,42,1,2,S,...,Oakland,CA,Alameda County,94607,US,Alameda,"5333 Adeline St , Oakland, CA 94608",37.838429,-122.275828,1.584193
3,Dirty Burger (Oakland),45–55 min,4.99,https://postmates.com/store/dirty-burger-oakla...,2236 Linden St Oakland CA,60014016002,42,1,2,S,...,Oakland,CA,Alameda County,94607,US,Alameda,"2353 East 12th Street, Oakland, CA 94601",37.781594,-122.235954,3.423599
4,iLava Hawaiian Barbecue (Adeline),35–45 min,3.99,https://postmates.com/store/ilava-hawaiian-bar...,2236 Linden St Oakland CA,60014016002,42,1,2,S,...,Oakland,CA,Alameda County,94607,US,Alameda,"5333 Adeline Street, Oakland, CA 94608",37.838429,-122.275828,1.584193
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44011,Loard's Ice Cream,35–45 min,5.49,https://postmates.com/store/loards-ice-cream/7...,9957 Medford Ave Oakland CA,60014093003,394,1,3,S,...,Oakland,CA,Alameda County,94603,US,Alameda,"2265 South Shore Center, Alameda, CA 94501",37.757734,-122.251968,4.368587
44012,Rite Aid (1355 Macarthur Blvd),40–50 min,2.99,https://postmates.com/store/rite-aid-1355-maca...,9957 Medford Ave Oakland CA,60014093003,394,1,3,S,...,Oakland,CA,Alameda County,94603,US,Alameda,"1355 Macarthur Blvd, San Leandro, CA 94577",37.729024,-122.139487,2.102078
44013,OakTown Wings,35–45 min,4.49,https://postmates.com/store/oaktown-wings/dj0V...,9957 Medford Ave Oakland CA,60014093003,394,1,3,S,...,Oakland,CA,Alameda County,94603,US,Alameda,"4481 International Blvd, Oakland, CA 94601",37.771301,-122.213378,3.065985
44014,Wingman,35–45 min,3.49,https://postmates.com/store/wingman/Oi2pmEDCTE...,9957 Medford Ave Oakland CA,60014093003,394,1,3,S,...,Oakland,CA,Alameda County,94603,US,Alameda,"6638 Bancroft Ave, Oakland, CA 94605",37.769835,-122.182269,2.213176
44015,Hong Kong Chef,35–45 min,3.49,https://postmates.com/store/hong-kong-chef/rlm...,9957 Medford Ave Oakland CA,60014093003,394,1,3,S,...,Oakland,CA,Alameda County,94603,US,Alameda,"1376 E 14th St, San Leandro, CA 94577",37.724565,-122.154874,1.492523

In [32]:
# Readin ACS demographic data
acs = pd.read_csv('ACS/acs_demographic_data.csv')
# Drop first column
acs = acs.drop(acs.columns[0], axis=1)
acs

,NAME_x,B03002_001E,B03002_002E,B03002_003E,B03002_004E,B03002_005E,B03002_006E,B03002_007E,B03002_008E,B03002_009E,...,pct_asian,pct_hisp,pct_other,median_income,pct_college,pct_hs_grad,pct_device_access,pct_internet_access,GEOID,GEOID_tract
0,"Block Group 1, Census Tract 4421, Alameda Coun...",2188,2154,212,78,5,1790,5,0,64,...,0.818099,0.015539,0.060786,92228.0,0.747654,0.935871,0.959509,0.950920,60014421001,6001442100
1,"Block Group 2, Census Tract 4421, Alameda Coun...",3274,3254,519,0,24,2609,25,11,66,...,0.796885,0.006109,0.051313,92228.0,0.747654,0.935871,0.959509,0.950920,60014421002,6001442100
2,"Block Group 4, Census Tract 4422, Alameda Coun...",1201,1109,384,57,18,600,9,0,41,...,0.499584,0.076603,0.075770,68202.0,0.664889,0.966279,0.988090,0.951478,60014422004,6001442200
3,"Block Group 3, Census Tract 4422, Alameda Coun...",1544,1524,344,0,0,1171,0,0,9,...,0.758420,0.012953,0.011658,68202.0,0.664889,0.966279,0.988090,0.951478,60014422003,6001442200
4,"Block Group 2, Census Tract 4422, Alameda Coun...",2296,2204,488,0,0,1656,0,0,60,...,0.721254,0.040070,0.052265,68202.0,0.664889,0.966279,0.988090,0.951478,60014422002,6001442200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1042,"Block Group 1, Census Tract 4501.01, Alameda C...",5750,5286,1837,255,22,2715,10,0,447,...,0.472174,0.080696,0.157217,85547.0,0.756948,0.964376,1.000000,0.956181,60014501011,6001450101
1043,"Block Group 1, Census Tract 4226, Alameda Coun...",1043,914,403,32,0,459,0,0,20,...,0.440077,0.123682,0.038351,4831.0,0.950355,1.000000,0.807692,0.653846,60014226001,6001422600
1044,"Block Group 1, Census Tract 4301.02, Alameda C...",2424,2126,1402,41,0,469,17,20,177,...,0.193482,0.122937,0.161304,68049.0,0.547694,0.965409,0.994444,0.974444,60014301021,6001430102
1045,"Block Group 0, Census Tract 9900, Alameda Coun...",0,0,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,60019900000,6001990000
1046,"Block Group 1, Census Tract 4029, Alameda Coun...",1406,1158,303,241,3,528,0,19,64,...,0.375533,0.176387,0.104552,23264.0,0.435391,0.790947,0.809273,0.750263,60014029001,6001402900

In [34]:
# Rename GEOID to Geoid in acs
acs = acs.rename(columns={'GEOID': 'Geoid'})
# Left join df and acs on Geoid
df_merged = pd.merge(df, acs, on='Geoid', how='left')
df_merged

,Name,Wait Time,Delivery Fee,Link,Delivery Address,Geoid,Unnamed: 0.1.1,Countyfp,Blkgrpce,Funcstat,...,pct_native,pct_asian,pct_hisp,pct_other,median_income,pct_college,pct_hs_grad,pct_device_access,pct_internet_access,GEOID_tract
0,Philly's Best (Jingletown),NaN,4.99,https://postmates.com/store/phillys-best-jingl...,2236 Linden St Oakland CA,60014016002,42,1,2,S,...,0.0,0.132167,0.103984,0.052478,37450.0,0.438177,0.872934,0.896205,0.775670,6001401600
1,Burger Latino (5333 Adeline St),35–45 min,3.99,https://postmates.com/store/burger-latino-5333...,2236 Linden St Oakland CA,60014016002,42,1,2,S,...,0.0,0.132167,0.103984,0.052478,37450.0,0.438177,0.872934,0.896205,0.775670,6001401600
2,"Philly Fresh Cheesesteaks (5333 Adeline St ,)",35–45 min,3.99,https://postmates.com/store/philly-fresh-chees...,2236 Linden St Oakland CA,60014016002,42,1,2,S,...,0.0,0.132167,0.103984,0.052478,37450.0,0.438177,0.872934,0.896205,0.775670,6001401600
3,Dirty Burger (Oakland),45–55 min,4.99,https://postmates.com/store/dirty-burger-oakla...,2236 Linden St Oakland CA,60014016002,42,1,2,S,...,0.0,0.132167,0.103984,0.052478,37450.0,0.438177,0.872934,0.896205,0.775670,6001401600
4,iLava Hawaiian Barbecue (Adeline),35–45 min,3.99,https://postmates.com/store/ilava-hawaiian-bar...,2236 Linden St Oakland CA,60014016002,42,1,2,S,...,0.0,0.132167,0.103984,0.052478,37450.0,0.438177,0.872934,0.896205,0.775670,6001401600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44011,Loard's Ice Cream,35–45 min,5.49,https://postmates.com/store/loards-ice-cream/7...,9957 Medford Ave Oakland CA,60014093003,394,1,3,S,...,0.0,0.120798,0.454832,0.163866,21622.0,0.140524,0.660092,0.876460,0.681008,6001409300
44012,Rite Aid (1355 Macarthur Blvd),40–50 min,2.99,https://postmates.com/store/rite-aid-1355-maca...,9957 Medford Ave Oakland CA,60014093003,394,1,3,S,...,0.0,0.120798,0.454832,0.163866,21622.0,0.140524,0.660092,0.876460,0.681008,6001409300
44013,OakTown Wings,35–45 min,4.49,https://postmates.com/store/oaktown-wings/dj0V...,9957 Medford Ave Oakland CA,60014093003,394,1,3,S,...,0.0,0.120798,0.454832,0.163866,21622.0,0.140524,0.660092,0.876460,0.681008,6001409300
44014,Wingman,35–45 min,3.49,https://postmates.com/store/wingman/Oi2pmEDCTE...,9957 Medford Ave Oakland CA,60014093003,394,1,3,S,...,0.0,0.120798,0.454832,0.163866,21622.0,0.140524,0.660092,0.876460,0.681008,6001409300
44015,Hong Kong Chef,35–45 min,3.49,https://postmates.com/store/hong-kong-chef/rlm...,9957 Medford Ave Oakland CA,60014093003,394,1,3,S,...,0.0,0.120798,0.454832,0.163866,21622.0,0.140524,0.660092,0.876460,0.681008,6001409300

In [25]:
# Read 'ACS/holc_grade.csv' using correct encoding
holc_grade = pd.read_csv('ACS/holc_grade_utf8.csv')
# holc = pd.read_csv('ACS/holc_grade.csv', sep=',')
holc_grade.head()

,County Cod,State Code,Census Tra,Geoid,Holc Grade,Holc Id,Id,Map Id,Msamd,Municipali,Name,Polygon Id,St Name,State,Year,Geometry,Holc Area,Holc Prop,Sheets,Tract Prop
0,1,6,421200,6001421200,B,B5,17,17,36084,NaN,NaN,6668,Oakland,CA,2019,Polygon,0.427333,0.024296,1,0.019836
1,1,6,402500,6001402500,D,D8,17,17,36084,NaN,NaN,6680,Oakland,CA,2019,Polygon,1.677309,0.007480,1,0.088914
2,1,6,423602,6001423602,B,B8,17,17,36084,NaN,NaN,6681,Oakland,CA,2019,Polygon,0.464799,0.118833,1,0.354818
3,1,6,400400,6001400400,B,B8,17,17,36084,NaN,NaN,6681,Oakland,CA,2019,Polygon,0.464799,0.000154,1,0.000264
4,1,6,421200,6001421200,B,B1,17,17,36084,NaN,NaN,6659,Oakland,CA,2019,Polygon,0.097637,0.003732,1,0.000696

In [26]:
# Read ACS/holc_tract_lookup_utf8.csv
holc_tract = pd.read_csv('ACS/holc_tract_lookup_utf8.csv')
holc_tract.head()

,the_geom,cartodb_id,polygon_id,geoid,tract_prop,holc_prop,state,city,name,neighborhood_id,holc_id
0,NaN,1,175,1073005910,0.031621,0.168091,AL,Birmingham,"Pittsburgh Addition, Vulcan Heights, Bibb Addi...",175,D16
1,NaN,2,3939,1097001302,0.018676,0.054642,AL,Mobile,Howell and Tuttle,3939,C1
2,NaN,3,614,6019002601,0.000094,0.000052,CA,Fresno,NaN,614,C5
3,NaN,4,7514,6037621400,0.001784,0.000155,CA,Los Angeles,NaN,7514,A59
4,NaN,5,6666,6001422300,0.000020,0.000012,CA,Oakland,NaN,6666,C3

In [38]:
# For each row in df_merged, get all the values in the column 'Holc Grade' where Geoid is equal to the Geoid in the row
df_merged['Holc Grade'] = df_merged.apply(lambda row: holc_grade[holc_grade['Geoid'] == row['Geoid']]['Holc Grade'].values, axis=1)